apiVersion: v1
kind: Service
metadata:
  name: freshbite-service
spec:
  type: NodePort               # Exposes on a high port
  selector:
    app: freshbite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080         